"""Generate src/sapi/voice_table.inc from the decoded ttvd VoiceDescriptions."""
import json, os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = sys.argv[1] if len(sys.argv) > 1 else \
    r'C:\Users\joshk\OneDrive\dev\sapivoice\src\sapi\voice_table.inc'

LCID = {
    'american': 0x0409, 'british': 0x0809, 'danish': 0x0406, 'german': 0x0407,
    'finnish': 0x040B, 'french': 0x040C, 'icelandic': 0x040F, 'italian': 0x0410,
    'norwegian': 0x0414, 'spanish': 0x040A, 'swedish': 0x041D,
}
LANG_LABEL = {
    'american': 'American English', 'british': 'British English',
    'danish': 'Dansk', 'german': 'Deutsch', 'finnish': 'Suomi',
    'french': 'Francais', 'icelandic': 'Islenska', 'italian': 'Italiano',
    'norwegian': 'Norsk', 'spanish': 'Espanol', 'swedish': 'Svenska',
}

def cstr(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == '\\':
            out.append('\\\\')
        elif ord(ch) < 0x20:
            out.append('?')
        elif ord(ch) < 0x7F:
            out.append(ch)
        elif ord(ch) < 0xA0:
            out.append('?')            # MSVC rejects \u below 0xA0
        else:
            # \u takes exactly four digits; \x would swallow a following hex
            # digit and produce an out-of-range escape.
            out.append('\\u%04x' % ord(ch))
    return ''.join(out)

voices = json.load(open(os.path.join(HERE, 'voices.json')))
voices.sort(key=lambda v: (v['pack'], v['resid']))

lines = []
lines.append('// Generated by tools/gen_voice_table.py from the engine\'s own ttvd')
lines.append('// VoiceDescription resources.  Do not edit by hand.')
lines.append('')
lines.append('static const voice_row kVoiceTable[] = {')
for v in voices:
    vid = struct.pack('>i', v['id']).decode('mac-roman')
    pack = v['pack']
    gender = {'male': 1, 'female': 2, 'neuter': 0}.get(str(v['gender']), 0)
    variant = int(vid[3])
    display = f'Infovox {v["name"]}'
    lines.append(
        '    {{ "{id}", "{pack}", L"{disp}", L"{lang}", 0x{lcid:04X}, {gender}, {age}, {variant} }},'
        .format(id=vid, pack=pack, disp=cstr(display), lang=cstr(LANG_LABEL[pack]),
                lcid=LCID[pack], gender=gender, age=v['age'], variant=variant))
lines.append('};')
lines.append('')
lines.append('// The configuration utility drives this one; its language, voice')
lines.append('// variant and every parameter come from the saved custom settings.')
lines.append('static const wchar_t kCustomVoiceName[] = L"Infovox 210 Custom Voice";')
lines.append('')
packs = sorted(set(v['pack'] for v in voices))
lines.append('static const char* const kPackNames[] = {')
for p in packs:
    lines.append(f'    "{p}",')
lines.append('};')
lines.append('')
lines.append('static const struct { const char* pack; const wchar_t* label; unsigned lcid; }')
lines.append('    kPackLabels[] = {')
for p in packs:
    lines.append(f'    {{ "{p}", L"{cstr(LANG_LABEL[p])}", 0x{LCID[p]:04X} }},')
lines.append('};')
lines.append('')

open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print(f'wrote {OUT}: {len(voices)} voices, {len(packs)} packs')
